export const ALLOWED_ORIGIN="https://keryas777.github.io";
export const ROUTE="/api/war-counter-vision/analyze";
export const LAYOUT="war-result-ultrawide-v1";
export const STRATEGIES=Object.freeze(["full_capture"]);
export const MAX_BYTES=12*1024*1024;
export const MAX_CATALOG_ITEMS=700;
export const DEFAULT_MODEL="qwen/qwen3.6-27b";
export const GROQ_ENDPOINT="https://api.groq.com/openai/v1/chat/completions";
const SLOT_ORDER=["left-1","left-2","left-3","left-4","left-5","right-1","right-2","right-3","right-4","right-5"];
const cors=o=>o===ALLOWED_ORIGIN?{"Access-Control-Allow-Origin":o,"Vary":"Origin"}:{};
const json=(body,status=200,o="")=>Response.json(body,{status,headers:{...cors(o),"Cache-Control":"no-store"}});
export const getVisionModel=env=>String(env?.GROQ_VISION_MODEL||DEFAULT_MODEL).trim()||DEFAULT_MODEL;
export const isMockMode=env=>["1","true"].includes(String(env?.R1_MOCK_ONLY??"").trim().toLowerCase());
export function validateCatalog(value){if(!Array.isArray(value)||value.length<1||value.length>MAX_CATALOG_ITEMS)throw new Error("Catalogue invalide.");const seen=new Set();return value.map(item=>{const id=String(item?.id||"").trim();const name=String(item?.name||item?.nameKey||"").trim();if(!id||!name||seen.has(id))throw new Error("Catalogue invalide.");seen.add(id);return{id,name};});}
export function buildVisionPrompt(catalog){return[
"Analyse cette capture de résultat de guerre Marvel Strike Force.",
"Elle contient exactement dix portraits: cinq à gauche puis cinq à droite.",
"Retourne uniquement un objet JSON, sans markdown ni commentaire.",
"Schéma exact: {\"schemaVersion\":\"2.0.0\",\"slots\":[{\"slot\":\"left-1\",\"barred\":false,\"candidates\":[{\"characterId\":\"ID\",\"confidence\":0.0}]}]}.",
"Fournis exactement 10 slots dans cet ordre: left-1,left-2,left-3,left-4,left-5,right-1,right-2,right-3,right-4,right-5.",
"Pour chaque slot, donne de 1 à 5 candidats classés du plus probable au moins probable.",
"barred vaut true si une croix rouge recouvre le portrait, false sinon, null seulement si impossible à déterminer.",
"Utilise exclusivement les characterId du catalogue autorisé ci-dessous. N'invente aucun identifiant.",
JSON.stringify(catalog)
].join("\n");}
export function buildGroqPayload({env,imageDataUrl,catalog}){if(!imageDataUrl?.startsWith("data:image/"))throw new Error("Image Vision invalide.");return{model:getVisionModel(env),messages:[{role:"user",content:[{type:"text",text:buildVisionPrompt(catalog)},{type:"image_url",image_url:{url:imageDataUrl}}]}],temperature:0,max_completion_tokens:4096,response_format:{type:"json_object"}};}
export function validateVisionResult(value,catalogIds){if(!value||value.schemaVersion!=="2.0.0"||!Array.isArray(value.slots)||value.slots.length!==10)throw new Error("Réponse Vision invalide.");const seen=new Set();value.slots.forEach((s,i)=>{if(s.slot!==SLOT_ORDER[i]||seen.has(s.slot))throw new Error("Slots invalides.");seen.add(s.slot);if(typeof s.barred!=="boolean"&&s.barred!==null)throw new Error("État barré invalide.");if(!Array.isArray(s.candidates)||s.candidates.length<1||s.candidates.length>5)throw new Error("Candidats invalides.");for(const c of s.candidates){if(!catalogIds.has(c.characterId))throw new Error("Candidat hors catalogue.");if(c.confidence!=null&&(!Number.isFinite(c.confidence)||c.confidence<0||c.confidence>1))throw new Error("Confiance invalide.");}});return true;}
export async function callGroqVision({env,payload,fetchImpl=fetch,timeoutMs=45000}){if(!env?.GROQ_API_KEY)throw new Error("GROQ_API_KEY absente.");const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const r=await fetchImpl(GROQ_ENDPOINT,{method:"POST",headers:{Authorization:`Bearer ${env.GROQ_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify(payload),signal:controller.signal});const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(`Groq ${r.status}: ${data?.error?.message||"erreur API"}`);const text=data?.choices?.[0]?.message?.content;if(typeof text!=="string")throw new Error("Réponse Groq vide.");let parsed;try{parsed=JSON.parse(text);}catch{throw new Error("JSON Groq invalide.");}return{parsed,usage:data.usage||null};}catch(e){if(e?.name==="AbortError")throw new Error("Timeout Groq Vision.");throw e;}finally{clearTimeout(timer);}}
const fileToDataUrl=async file=>{const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return`data:${file.type};base64,${btoa(binary)}`;};
export default{async fetch(request,env){const url=new URL(request.url),origin=request.headers.get("Origin")||"";if(request.method==="OPTIONS")return new Response(null,{status:204,headers:{...cors(origin),"Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"}});if(url.pathname!==ROUTE)return json({ok:false,error:"Not found"},404,origin);if(request.method!=="POST")return json({ok:false,error:"Method not allowed"},405,origin);if(origin&&origin!==ALLOWED_ORIGIN)return json({ok:false,error:"Origin interdite"},403,origin);if(!(request.headers.get("Content-Type")||"").includes("multipart/form-data"))return json({ok:false,error:"multipart/form-data requis"},415,origin);try{const form=await request.formData(),image=form.get("image"),strategy=String(form.get("strategy")||""),layout=String(form.get("layout")||""),confirmed=String(form.get("confirmed")||"");if(!(image instanceof File)||!["image/jpeg","image/png","image/webp"].includes(image.type)||image.size<=0||image.size>MAX_BYTES)return json({ok:false,error:"Image invalide"},400,origin);if(layout!==LAYOUT)return json({ok:false,error:"Layout invalide"},400,origin);if(!STRATEGIES.includes(strategy))return json({ok:false,error:"Seule la stratégie full_capture est autorisée en R3"},400,origin);if(confirmed!=="one-real-call")return json({ok:false,error:"Confirmation explicite requise"},400,origin);if(isMockMode(env))return json({ok:false,error:"R3 verrouillée par R1_MOCK_ONLY",groqRealCalls:0},503,origin);const catalog=validateCatalog(JSON.parse(String(form.get("catalog")||"null")));const started=Date.now();const payload=buildGroqPayload({env,imageDataUrl:await fileToDataUrl(image),catalog});const result=await callGroqVision({env,payload});validateVisionResult(result.parsed,new Set(catalog.map(item=>item.id)));return json({ok:true,result:{...result.parsed,provider:"groq",model:getVisionModel(env),strategy,groqRealCalls:1,durationMs:Date.now()-started,usage:result.usage}},200,origin);}catch(error){return json({ok:false,error:error?.message||"Erreur Worker",groqRealCalls:0},502,origin);}}};
