export const ALLOWED_ORIGIN="https://keryas777.github.io";
export const ROUTE="/api/war-counter-vision/analyze";
export const LAYOUT="war-result-ultrawide-v1";
export const STRATEGIES=Object.freeze(["full_capture","grouped_wide_crops","grouped_tight_crops","individual_crop"]);
export const MAX_BYTES=12*1024*1024;
export const DEFAULT_MODEL="qwen/qwen3.6-27b";
export const GROQ_ENDPOINT="https://api.groq.com/openai/v1/chat/completions";
const SLOT_ORDER=["left-1","left-2","left-3","left-4","left-5","right-1","right-2","right-3","right-4","right-5"];
const cors=o=>o===ALLOWED_ORIGIN?{"Access-Control-Allow-Origin":o,"Vary":"Origin"}:{};
const json=(body,status=200,o="")=>Response.json(body,{status,headers:{...cors(o),"Cache-Control":"no-store"}});
export const getVisionModel=env=>String(env?.GROQ_VISION_MODEL||DEFAULT_MODEL).trim()||DEFAULT_MODEL;
export function buildVisionPrompt(catalog){return[`Analyse une capture de résultat de guerre Marvel Strike Force contenant exactement dix portraits.`,`Retourne uniquement un JSON conforme au schéma demandé, dans l’ordre left-1 à left-5 puis right-1 à right-5.`,`Chaque candidat doit utiliser un characterId présent dans ce catalogue autorisé: ${catalog.map(x=>x.id).join(",")}.`,`Une croix rouge peut recouvrir un portrait. Ne crée aucun personnage hors catalogue.`].join("\n");}
export function buildGroqPayload({env,imageDataUrl,catalog}){if(!imageDataUrl?.startsWith("data:image/"))throw new Error("Image Vision invalide.");return{model:getVisionModel(env),messages:[{role:"user",content:[{type:"text",text:buildVisionPrompt(catalog)},{type:"image_url",image_url:{url:imageDataUrl}}]}],temperature:0,response_format:{type:"json_object"}};}
export function validateVisionResult(value,catalogIds){if(!value||value.schemaVersion!=="2.0.0"||!Array.isArray(value.slots)||value.slots.length!==10)throw new Error("Réponse Vision invalide.");const seen=new Set();value.slots.forEach((s,i)=>{if(s.slot!==SLOT_ORDER[i]||seen.has(s.slot))throw new Error("Slots invalides.");seen.add(s.slot);if(typeof s.barred!=="boolean"&&s.barred!==null)throw new Error("État barré invalide.");if(!Array.isArray(s.candidates)||s.candidates.length<1||s.candidates.length>5)throw new Error("Candidats invalides.");for(const c of s.candidates){if(!catalogIds.has(c.characterId))throw new Error("Candidat hors catalogue.");if(c.confidence!=null&&(!Number.isFinite(c.confidence)||c.confidence<0||c.confidence>1))throw new Error("Confiance invalide.");}});return true;}
export async function callGroqVision({env,payload,fetchImpl=fetch,timeoutMs=45000}){if(!env?.GROQ_API_KEY)throw new Error("GROQ_API_KEY absente.");const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const r=await fetchImpl(GROQ_ENDPOINT,{method:"POST",headers:{Authorization:`Bearer ${env.GROQ_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify(payload),signal:controller.signal});const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(`Groq ${r.status}: ${data?.error?.message||"erreur API"}`);const text=data?.choices?.[0]?.message?.content;if(typeof text!=="string")throw new Error("Réponse Groq vide.");let parsed;try{parsed=JSON.parse(text);}catch{throw new Error("JSON Groq invalide.");}return{parsed,usage:data.usage||null};}catch(e){if(e?.name==="AbortError")throw new Error("Timeout Groq Vision.");throw e;}finally{clearTimeout(timer);}}
export function createMockResponse(strategy="full_capture"){return{schemaVersion:"2.0.0",provider:"mock",model:DEFAULT_MODEL,strategy,groqRealCalls:0,durationMs:0,usage:null,slots:SLOT_ORDER.map(slot=>({slot,barred:null,candidates:[{characterId:"AgentVenom",confidence:0}]}))};}
export default{async fetch(request,env){const url=new URL(request.url),origin=request.headers.get("Origin")||"";if(request.method==="OPTIONS")return new Response(null,{status:204,headers:{...cors(origin),"Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"}});if(url.pathname!==ROUTE)return json({ok:false,error:"Not found"},404,origin);if(request.method!=="POST")return json({ok:false,error:"Method not allowed"},405,origin);if(origin&&origin!==ALLOWED_ORIGIN)return json({ok:false,error:"Origin interdite"},403,origin);if(!(request.headers.get("Content-Type")||"").includes("multipart/form-data"))return json({ok:false,error:"multipart/form-data requis"},415,origin);const form=await request.formData(),image=form.get("image"),strategy=String(form.get("strategy")||""),layout=String(form.get("layout")||"");if(!(image instanceof File)||!["image/jpeg","image/png","image/webp"].includes(image.type)||image.size<=0||image.size>MAX_BYTES)return json({ok:false,error:"Image invalide"},400,origin);if(layout!==LAYOUT)return json({ok:false,error:"Layout invalide"},400,origin);if(!STRATEGIES.includes(strategy))return json({ok:false,error:"Stratégie invalide"},400,origin);if(env?.WAR_COUNTER_VISION_MOCK!=="1")return json({ok:false,error:"Groq réel désactivé pendant R2",groqRealCalls:0},503,origin);return json({ok:true,result:createMockResponse(strategy)},200,origin);}};
