export const ALLOWED_ORIGIN="https://keryas777.github.io";
export const ROUTE="/api/war-counter-vision/analyze";
export const LAYOUT="war-result-ultrawide-v1";
export const STRATEGIES=Object.freeze(["full_capture","grouped_wide_crops","grouped_tight_crops","individual_crop"]);
export const MAX_BYTES=12*1024*1024;
function cors(origin){return origin===ALLOWED_ORIGIN?{"Access-Control-Allow-Origin":origin,"Vary":"Origin"}:{}}
function json(body,status=200,origin=""){return Response.json(body,{status,headers:{...cors(origin),"Cache-Control":"no-store"}})}
export function validateMockResponse(value){if(!value||value.schemaVersion!=="1.0.0"||value.provider!=="mock"||value.groqRealCalls!==0)throw new Error("Réponse R1 invalide.");if(!Array.isArray(value.slots)||value.slots.length!==10)throw new Error("Dix slots requis.");const expected=["left-1","left-2","left-3","left-4","left-5","right-1","right-2","right-3","right-4","right-5"],seen=new Set();value.slots.forEach((slot,index)=>{if(slot.slot!==expected[index]||seen.has(slot.slot))throw new Error("Slots invalides.");seen.add(slot.slot);if(!Array.isArray(slot.candidates))throw new Error("Candidats invalides.")});return true}
export function createMockResponse(strategy){return{schemaVersion:"1.0.0",provider:"mock",model:"qwen/qwen3.6-27b",strategy,groqRealCalls:0,slots:["left-1","left-2","left-3","left-4","left-5","right-1","right-2","right-3","right-4","right-5"].map((slot)=>({slot,candidates:[],barred:null}))}}
export default{async fetch(request){const url=new URL(request.url),origin=request.headers.get("Origin")||"";if(request.method==="OPTIONS")return new Response(null,{status:204,headers:{...cors(origin),"Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"}});if(url.pathname!==ROUTE)return json({ok:false,error:"Not found"},404,origin);if(request.method!=="POST")return json({ok:false,error:"Method not allowed"},405,origin);if(origin&&origin!==ALLOWED_ORIGIN)return json({ok:false,error:"Origin interdite"},403,origin);const type=request.headers.get("Content-Type")||"";if(!type.includes("multipart/form-data"))return json({ok:false,error:"multipart/form-data requis"},415,origin);const form=await request.formData(),image=form.get("image"),strategy=String(form.get("strategy")||""),layout=String(form.get("layout")||"");if(!(image instanceof File)||!image.type.startsWith("image/")||image.size<=0||image.size>MAX_BYTES)return json({ok:false,error:"Image invalide"},400,origin);if(layout!==LAYOUT)return json({ok:false,error:"Layout invalide"},400,origin);if(!STRATEGIES.includes(strategy))return json({ok:false,error:"Stratégie invalide"},400,origin);const response=createMockResponse(strategy);validateMockResponse(response);return json({ok:true,result:response},200,origin)}};
