name: Update infos.json

on:
  workflow_dispatch:
  schedule:
    - cron: "15 */6 * * *" # toutes les 6h (à 00:15, 06:15, 12:15, 18:15)
  push:
    paths:
      - "scripts/sheets-infos.mjs"
      - ".github/workflows/infos.yml"

permissions:
  contents: write

concurrency:
  group: update-infos-json
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate docs/data/infos.json
        env:
          OUT_FILE: docs/data/infos.json
          INFOS_CSV_URL: https://docs.google.com/spreadsheets/d/e/2PACX-1vTYKGvuHFRrB59aW6oMHBVFTRBdHhxxZP76YmwlpedoepMftwst1MfCwLg7pMLCPsGOpSrADdLzntQH/pub?gid=2000709341&single=true&output=csv
          # 🔁 Mets ici ton lien "Joueurs" publié sur le web (output=csv)
          JOUEURS_CSV_URL: ${{ secrets.JOUEURS_CSV_URL }}
        run: node scripts/sheets-infos.mjs

      - name: Commit & push if changed
        run: |
          if git diff --quiet -- docs/data/infos.json; then
            echo "No changes in docs/data/infos.json"
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/data/infos.json
          git commit -m "Update infos.json"
          git push
